MailboxSync/Controllers/NotificationController.cs
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Configuration;
using System.Security.Claims;
using System.Web.Mvc;
using System.Threading.Tasks;
using MailboxSync.Helpers;
using MailboxSync.Models;
using MailboxSync.Services;
using MailboxSync.Services.SignalR;

namespace MailboxSync.Controllers
{
    public class NotificationController : Controller
    {
        public static string ClientId = ConfigurationManager.AppSettings["ida:ClientId"];

        /// <summary>
        /// Store the notifications in session state. A production
        /// application would likely queue for additional processing.
        /// </summary>
        /// <returns></returns>
        [Authorize]
        public ActionResult Index()
        {
            ViewBag.CurrentUserId = ClaimsPrincipal.Current.FindFirst(ClaimTypes.NameIdentifier).Value;


            var notificationArray = (ConcurrentBag<NotificationItem>)HttpContext.Application["notifications"];
            if (notificationArray == null)
            {
                notificationArray = new ConcurrentBag<NotificationItem>();
            }
            HttpContext.Application["notifications"] = notificationArray;
            return View(notificationArray);
        }

        /// <summary>
        /// The `notificationUrl` endpoint that's registered with the webhook subscription.
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public async Task<ActionResult> Listen()
        {

            // Validate the new subscription by sending the token back to Microsoft Graph.
            // This response is required for each subscription.
            if (Request.QueryString["validationToken"] != null)
            {
                var token = Request.QueryString["validationToken"];
                return Content(token, "plain/text");
            }

            // Parse the received notifications.
            else
            {
                try
                {
                    using (var inputStream = new System.IO.StreamReader(Request.InputStream))
                    {
                        JObject jsonObject = JObject.Parse(inputStream.ReadToEnd());
                        var notificationArray = (ConcurrentBag<NotificationItem>)HttpContext.Application["notifications"];

                        if (jsonObject != null)
                        {

                            // Notifications are sent in a 'value' array. The array might contain multiple notifications for events that are
                            // registered for the same notification endpoint, and that occur within a short timespan.
                            JArray value = JArray.Parse(jsonObject["value"].ToString());
                            foreach (var notification in value)
                            {
                                NotificationItem current = JsonConvert.DeserializeObject<NotificationItem>(notification.ToString());

                                // Check client state to verify the message is from Microsoft Graph. 
                                SubscriptionStore subscription = SubscriptionStore.GetSubscriptionInfo(current.SubscriptionId);

                                // This sample only works with subscriptions that are still cached.
                                if (subscription != null)
                                {
                                    if (current.ClientState == subscription.ClientState)
                                    {
                                        //Store the notifications in application state. A production
                                        //application would likely queue for additional processing.                                                                             
                                        if (notificationArray == null)
                                        {
                                            notificationArray = new ConcurrentBag<NotificationItem>();
                                        }
                                        notificationArray.Add(current);
                                        HttpContext.Application["notifications"] = notificationArray;
                                    }
                                }
                            }

                            if (notificationArray.Count > 0)
                            {
                                await GetChangedMessagesAsync(notificationArray);
                            }
                        }
                    }
                }
                catch (Exception)
                {
                    // ignored
                }

                return new HttpStatusCodeResult(202);
            }
        }


        /// <summary>
        /// Get the changed message details 
        /// Update the local json file
        /// Continue to update the UI using SignalR
        /// </summary>
        /// <param name="notifications"></param>
        /// <returns></returns>
        public async Task GetChangedMessagesAsync(IEnumerable<NotificationItem> notifications)
        {
            DataService dataService = new DataService();
            MailService mailService = new MailService();
            int newMessages = 0;
            foreach (var notification in notifications)
            {
                var subscription = SubscriptionStore.GetSubscriptionInfo(notification.SubscriptionId);

                var graphClient = GraphServiceClientProvider.GetAuthenticatedClient(subscription.UserId);

                try
                {
                    // Get the message
                    var message = await mailService.GetMessage(graphClient, notification.ResourceData.Id);

                    // update the local json file
                    if (message != null)
                    {
                        var messageItem = new MessageItem
                        {
                            BodyPreview = message.BodyPreview,
                            ChangeKey = message.ChangeKey,
                            ConversationId = message.ConversationId,
                            CreatedDateTime = (DateTimeOffset)message.CreatedDateTime,
                            Id = message.Id,
                            IsRead = (bool)message.IsRead,
                            Subject = message.Subject
                        };
                        var messageItems = new List<MessageItem> { messageItem };
                        dataService.StoreMessage(messageItems, message.ParentFolderId, null);
                        newMessages += 1;

                    }
                }
                catch (Exception e)
                {
                    // ignored
                }
            }

            if (newMessages > 0)
            {
                NotificationService notificationService = new NotificationService();
                notificationService.SendNotificationToClient();
            }
        }
    }
}

MailboxSync/Views/Shared/_Layout.cshtml
<!--  Copyright (c) Microsoft. All rights reserved. Licensed under the MIT license.
        See LICENSE in the source repository root for complete license information. -->

@{
    ViewBag.AppName = "Mailbox Sync";
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css")
    @Styles.Render("https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap-theme.min.css")
    @Scripts.Render("https://ajax.aspnetcdn.com/ajax/modernizr/modernizr-2.6.2.js")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Mailbox Sync", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Notifications", "Index", "Notification")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
<div class="container body-content">
    @RenderBody()
    <hr/>
    <footer>
        <p>&copy; @DateTime.Now.Year - Microsoft - Microsoft Graph Sample - @ViewBag.AppName</p>
    </footer>
</div>
    @Scripts.Render("~/Scripts/ui-helpers.js")
    @Scripts.Render("https://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.2.1.min.js")
    @Scripts.Render("https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js")
    @RenderSection("scripts", required: false)
    <script src="~/signalr/hubs"></script>
</body>
</html>

MailboxSync/Views/Shared/_ResultsPartial.cshtml
<!--  Copyright (c) Microsoft. All rights reserved. Licensed under the MIT license.
        See LICENSE in the source repository root for complete license information. -->


@model MailboxSync.Models.FoldersViewModel

<div class="col-md-12">
    <h3>Mailbox:</h3>
    <div class="col-md-12">
        <div class="container">

            @if (Model != null)
            {
                if (Model.Items.Any())
                {
                    int count = 0;

                    <ul class="nav nav-pills nav-stacked col-md-3">
                        @foreach (var item in Model.Items)
                        {
                            <li class="@(count==0 ? "active":"")">
                                <a href="#@count" data-toggle="pill">
                                    &nbsp;@item.Name
                                    <span class="pull-right badge"> @(item.MessageItems == null ? 0 : item.MessageItems.Count) </span>
                                </a>
                            </li>
                            count++;
                        }
                    </ul>
                    <div class="tab-content col-md-9">
                        @{
                            int messageCount = 0;
                            foreach (var item in Model.Items)
                            {
                                <div class="@(messageCount==0 ? "tab-pane active":"tab-pane")" id="@messageCount">
                                    <h4>&nbsp;@item.Name</h4>
                                    <hr>
                                    @if (item.MessageItems != null && item.MessageItems.Count > 0)
                                    {
                                        <div class="row" id="table-@item.Id">
                                            <div class="col-md-12" style="font-weight:800;text-decoration:underline;">
                                                <div class="col-md-6">Subject</div>
                                                <div class="col-md-4">Created</div>
                                                <div class="col-md-2">Opened</div>
                                            </div>
                                            <hr />
                                            @foreach (var message in item.MessageItems)
                                            {
                                                var messageStyle = "border-bottom:solid #ddd 1px;padding:10px;";
                                                if (!@message.IsRead)
                                                {
                                                    messageStyle = messageStyle + "font-weight:bold";
                                                }
                                                <div class="col-md-12" title="@message.BodyPreview" style="@messageStyle">
                                                    <div class="col-md-6">@message.Subject</div>
                                                    <div class="col-md-4">@message.CreatedDateTime</div>
                                                    <div class="col-md-2">@message.IsRead</div>

                                                </div>
                                            }
                                        </div>
                                        <br />
                                    }
                                    <hr>
                                    <div>
                                        @using (Html.BeginForm("GetPagedMessages", "Home"))
                                        {
                                            <button class="btn btn-link needs-id" id="get-message">Load More</button>
                                            <input class="selected-id" value=@item.Id name="folderId" type="hidden" />
                                            <input class="selected-id" value=@item.SkipToken name="skipToken" type="hidden" />

                                        }
                                    </div>

                                </div>
                                messageCount++;
                            }
                        }
                    </div>


                }
                else
                {
                    <p>Operation completed, but no results were returned.</p>
                }
            }

        </div>
    </div>
    <br />
</div>